### ISSUE TITLE
Using the Audio Device Renamer crash the extension 

### ISSUE THREAD

**Issue by AXL1994** [marcinjahn/gnome-quicksetings-audio-devices-hider-extension#8]
I have some extensions enabled, and they all work great with the device audio hider extension. Since I installed the Audio Device Renamer this extension crash randomly, so when I turn on the pc everything is ok, but after a while it crash. I suppose there is some incompatibility.

**Comment by marcinjahn** [comment]
Hi @AXL1994, I have actually observed a similar issue. Recently, I’ve released v10 of Hider, which has a chance of getting rid of those crashes. Make sure you’re running that new version.

**Comment by AXL1994** [comment]
I think I already had the v10, my extension manager didn't show any update. I waited 24 hours though, and today I didn't had any crash. So maybe there isn't any problem anymore? Maybe it's better to wait some days, if nothing happen I just close the issue!

**Comment by marcinjahn** [comment]
V10 was submitted to Gnome Extensions a day before you opened the issue, not sure when it was actually released as an update.

Alright, thanks!

**Comment by AXL1994** [comment]
Nope, the extension just crashed and I have Hider v10! Is there a way to get some logs for you?

**Comment by marcinjahn** [comment]
You could check in the Extensions app (I assume you have [this one](https://flathub.org/apps/com.mattjakeman.ExtensionManager). There should be a way to extend the details of the error. 
I guess it will say “this._audioPanel is null”.

**Comment by AXL1994** [comment]
Yes, it was exactly that error. I checked the registry and found this, maybe it's useful

```
JS ERROR: Extension quicksettings-audio-devices-hider@marcinjahn.com: TypeError: this._audioPanel is null
setInputsMapInSettings@/home/alessandro/.local/share/gnome-shell/extensions/quicksettings-audio-devices-renamer@marcinjahn.com/extension.js:463:33
setupAudioPanelChangesSubscription/this._audioPanelOutputsSub<@/home/alessandro/.local/share/gnome-shell/extensions/quicksettings-audio-devices-renamer@marcinjahn.com/extension.js:399:22
set@/home/alessandro/.local/share/gnome-shell/extensions/quicksettings-audio-devices-renamer@marcinjahn.com/extension.js:51:17
_addDevice@resource:///org/gnome/shell/ui/status/volume.js:140:27
addDevice@/home/alessandro/.local/share/gnome-shell/extensions/quicksettings-audio-devices-hider@marcinjahn.com/extension.js:50:46
enableAllDevices/<@/home/alessandro/.local/share/gnome-shell/extensions/quicksettings-audio-devices-hider@marcinjahn.com/extension.js:432:61
enableAllDevices@/home/alessandro/.local/share/gnome-shell/extensions/quicksettings-audio-devices-hider@marcinjahn.com/extension.js:432:18
disable@/home/alessandro/.local/share/gnome-shell/extensions/quicksettings-audio-devices-hider@marcinjahn.com/extension.js:407:18
_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:132:32
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:565:24
async*_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:717:20
ExtensionManager/<@resource:///org/gnome/shell/ui/extensionSystem.js:36:18
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_sync@resource:///org/gnome/shell/ui/sessionMode.js:208:14
pushMode@resource:///org/gnome/shell/ui/sessionMode.js:167:14
activate@resource:///org/gnome/shell/ui/screenShield.js:617:34
_onLongLightbox@resource:///org/gnome/shell/ui/screenShield.js:336:18
onComplete@resource:///org/gnome/shell/ui/lightbox.js:198:18
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:153:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:240:64
```

**Comment by marcinjahn** [comment]
Right, that’s the same thing I saw on my system. Thanks for confirming that with the the logs :)

I’ll try to have a look at this issue in the coming days.

**Comment by marcinjahn** [comment]
I released V2 of [Renamer](https://github.com/marcinjahn/gnome-quicksettings-audio-devices-renamer-extension). It should make the crashes go away.

**Comment by AXL1994** [comment]
So far so good, I didn't have any crash, I'll wait a couple of days just to be sure! Great work :)

**Comment by AXL1994** [comment]
Ok, it didn't crash since the last update, I can considered it fixed! Thanks again, mate! :)

**Comment by marcinjahn** [comment]
Cool, thanks for the confirmation.

Consider starring the repository if you find my work useful.
